spring.application.name=gerenciadorcaixas 

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciadorcaixas
spring.datasource.username=postgres
spring.datasource.password=postgres
srping.jpa.hibernate.ddl-auto=update