spring.application.name=gerenciadorcaixas

# URL - Usando H2 (banco em memória)
spring.datasource.url=jdbc:h2:mem:gerenciadorcaixas # banco em memória
# spring.datasource.url=jdbc:h2:file:./data/gerenciadorcaixas # persistir em arquivo

# DRIVER
spring.datasource.driver-class-name=org.h2.Driver

# USERNAME
spring.datasource.username=sa

# SENHA
spring.datasource.password=postgre

# CONFIGURAÇÕES
# JPA: cria as tabelas automaticamente a partir das @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra os SQLs gerados
spring.jpa.show-sql=true

# Avisa pro hibernate o formato do SQL PARA O BANCO USADO
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.h2

# Console web do h2 (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mudar o path dos docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
 
# Ordenar endpoints alfabeticamente
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha