spring.application.name=gerenciadorcaixas

# Datasource H2 em memória
spring.datasource.url=jdbc:h2:mem:gerenciadorcaixas # banco em memória
# spring.datasource.url=jdbc:h2:file:./data/gerenciadorcaixas # persistir em arquivo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=postgre

# JPA: cria as tabelas automaticamente a partir das @Entity
spring.jpa.hibernate.ddl-auto=update

# mostra os SQLs gerados
spring.jpa.show-sql=true


# Console web do h2 (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mudar o path dos docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
 
# Ordenar endpoints alfabeticamente
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha